from typing import NamedTuple


class SandwichPattern(NamedTuple):
    middle_x: str
    middle_y: str
    beginning_options: frozenset[str]
    end_options: frozenset[str]
    min_length: int


IPA_PATTERNS = {
    SandwichPattern(
        'aʊ',
        'oʊuə',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'ə',
        'ʊ',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        3,
    ),
    SandwichPattern(
        'eɪ',
        'ɑ',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        5,
    ),
    SandwichPattern(
        'eɪ',
        'aɪ',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        5,
    ),
    SandwichPattern(
        'eɪ',
        'i',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'eɪ',
        'j',
        frozenset({'k'}),
        frozenset({'s'}),
        5,
    ),
    SandwichPattern(
        'i',
        'aɪ',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'i',
        'j',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'i',
        'ɪɛ',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'i',
        'ɪ',
        frozenset({'l'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'i',
        'ɪ',
        frozenset({'l', 'r'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'i',
        'ɪ',
        frozenset({'r'}),
        frozenset({'k'}),
        5,
    ),
    SandwichPattern(
        'i',
        'ə',
        frozenset({'m'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'i',
        'ɪ',
        frozenset({'m'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'i',
        'aɪ',
        frozenset({'v'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'i',
        'ɛ',
        frozenset({'h'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'i',
        'eɪ',
        frozenset({'z'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'i',
        'ə',
        frozenset({'k'}),
        frozenset({'r-'}),
        0,
    ),
    SandwichPattern(
        'oʊ',
        'ɔ',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'oʊ',
        'aʊə',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'oʊ',
        'u',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'r'}),
        5,
    ),
    SandwichPattern(
        'oʊ',
        'oʊw',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'r',
        'ər',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        's',
        'z',
        frozenset({'ɑ', 'a', 'æ', 'ɪ', 'i', 'ɛ', 'e', 'ə', 'ɔ', 'ʊ', 'u', 'o'}),
        frozenset({'-'}),
        4,
    ),
    SandwichPattern(
        'th',
        'θ',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'ɑ', 'a', 'æ', 'ɪ', 'i', 'ɛ', 'e', 'ə', 'ɔ', 'ʊ', 'u', 'o'}),
        5,
    ),
    SandwichPattern(
        'u',
        'ju',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'u',
        'au',
        frozenset({'n'}),
        frozenset({'m'}),
        0,
    ),
    SandwichPattern(
        'u',
        'aʊ',
        frozenset({'n'}),
        frozenset({'m'}),
        0,
    ),
    SandwichPattern(
        'uə',
        'ɔ',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'r'}),
        0,
    ),
    SandwichPattern(
        'z',
        'st',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'z',
        'ɛs',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-'}),
        4,
    ),
    SandwichPattern(
        'z',
        's',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        5,
    ),
    SandwichPattern(
        'æ',
        'eɪ',
        frozenset({'-'}),
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        5,
    ),
    SandwichPattern(
        'æ',
        'ɑ',
        frozenset({'k'}),
        frozenset({'k'}),
        0,
    ),
    SandwichPattern(
        'æ',
        'ɑ',
        frozenset({'g'}),
        frozenset({'r'}),
        0,
    ),
    SandwichPattern(
        'æ',
        'ɑ',
        frozenset({'b'}),
        frozenset({'k-'}),
        0,
    ),
    SandwichPattern(
        'æ',
        'ɑ',
        frozenset({'r'}),
        frozenset({'m'}),
        0,
    ),
    SandwichPattern(
        'æ',
        'ɑ',
        frozenset({'r'}),
        frozenset({'b'}),
        0,
    ),
    SandwichPattern(
        'æ',
        'ə',
        frozenset({'m'}),
        frozenset({'n-'}),
        5,
    ),
    SandwichPattern(
        'æ',
        'ɑ',
        frozenset({'m'}),
        frozenset({'n-'}),
        5,
    ),
    SandwichPattern(
        'æ',
        'ɑh',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'æŋ',
        'ɛng',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'ɑ',
        'aɪ',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        6,
    ),
    SandwichPattern(
        'ɑriə',
        'əraɪə',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'ɔ',
        'ɑ',
        frozenset({'n'}),
        frozenset({'n'}),
        0,
    ),
    SandwichPattern(
        'ə',
        'ɪ',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        5,
    ),
    SandwichPattern(
        'ə',
        'eɪ',
        frozenset({'z'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'ə',
        'ɔ',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'n'}),
        0,
    ),
    SandwichPattern(
        'ə',
        'ʊ',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'r'}),
        0,
    ),
    SandwichPattern(
        'ə',
        'ɔ',
        frozenset({'f'}),
        frozenset({'r'}),
        5,
    ),
    SandwichPattern(
        'ɛ',
        'j',
        frozenset({'l'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'ɛ',
        'i',
        frozenset({'l'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'ɛ',
        'ɪ',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'ld'}),
        0,
    ),
    SandwichPattern(
        'ɛ',
        'ɪ',
        frozenset({'l'}),
        frozenset({'t'}),
        5,
    ),
    SandwichPattern(
        'ɛ',
        'ɪ',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'d'}),
        5,
    ),
    SandwichPattern(
        'ɛ',
        'ɑ',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'r'}),
        5,
    ),
    SandwichPattern(
        'ɛ',
        'æ',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'r'}),
        5,
    ),
    SandwichPattern(
        'ɛ',
        'ə',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'r'}),
        0,
    ),
    SandwichPattern(
        'ɛ',
        'ə',
        frozenset({'s'}),
        frozenset({'n'}),
        5,
    ),
    SandwichPattern(
        'ɛ',
        'aɪ',
        frozenset({'ʤ'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'ɪ',
        'j',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'ɪn',
        'im',
        frozenset({'ks'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'ɪs',
        'iz',
        frozenset({'n'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'lts',
        'l',
        frozenset({'ɑ', 'a', 'æ', 'ɪ', 'i', 'ɛ', 'e', 'ə', 'ɔ', 'ʊ', 'u', 'o'}),
        frozenset({'-'}),
        3,
    ),
    SandwichPattern(
        'ʊ',
        'ɔ',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'ər',
        'r',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        4,
    ),
    SandwichPattern(
        'kə',
        'k',
        frozenset({'-'}),
        frozenset({'n'}),
        4,
    ),
    SandwichPattern(
        'ə',
        'u',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        4,
    ),
    SandwichPattern(
        'hɛnrɪ',
        'ɑnrɪ',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'ə',
        'ju',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'oʊs',
        'ɔz',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'oʊz',
        'ɔs',
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'-', 'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        0,
    ),
    SandwichPattern(
        'ma',
        'm',
        frozenset({'ʃ'}),
        frozenset({'ɪ'}),
        0,
    ),
    SandwichPattern(
        'oʊ',
        'ɑ',
        frozenset({'b'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'ɔ',
        'ə',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'r'}),
        0,
    ),
    SandwichPattern(
        'ɑ',
        'ə',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'r'}),
        5,
    ),
    SandwichPattern(
        'ɔ',
        'ə',
        frozenset({'l', 'd', 'z', 'b', 't', 'k', 'n', 's', 'w', 'v', 'ð', 'ʒ', 'ʧ', 'θ', 'h', 'g', 'ʤ', 'ŋ', 'p', 'm', 'ʃ', 'f', 'j', 'r'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'f',
        'voʊ',
        frozenset({'ɑ', 'a', 'æ', 'ɪ', 'i', 'ɛ', 'e', 'ə', 'ɔ', 'ʊ', 'u', 'o'}),
        frozenset({'-'}),
        5,
    )
}


SPELLING_PATTERNS = {
    SandwichPattern(
        'a',
        'o',
        frozenset({'n'}),
        frozenset({'n'}),
        6,
    ),
    SandwichPattern(
        'a',
        'e',
        frozenset({'h'}),
        frozenset({'lm'}),
        6,
    ),
    SandwichPattern(
        'a',
        'e',
        frozenset({'r'}),
        frozenset({'n-'}),
        6,
    ),
    SandwichPattern(
        'a',
        'e',
        frozenset({'l'}),
        frozenset({'y-'}),
        0,
    ),
    SandwichPattern(
        'ae',
        'ey',
        frozenset({'-', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        0,
    ),
    SandwichPattern(
        'ae',
        'aa',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        0,
    ),
    SandwichPattern(
        'ai',
        'a',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'th-'}),
        4,
    ),
    SandwichPattern(
        'ai',
        'a',
        frozenset({'b'}),
        frozenset({'t'}),
        6,
    ),
    SandwichPattern(
        'asure',
        'azer',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'aw',
        'au',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        0,
    ),
    SandwichPattern(
        'ay',
        'a',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        4,
    ),
    SandwichPattern(
        'c',
        's',
        frozenset({'t'}),
        frozenset({'h'}),
        4,
    ),
    SandwichPattern(
        'cc',
        'c',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        4,
    ),
    SandwichPattern(
        'ce',
        'sa',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        5,
    ),
    SandwichPattern(
        'ch',
        'ck',
        frozenset({'a'}),
        frozenset({'s'}),
        0,
    ),
    SandwichPattern(
        'ch',
        'k',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        5,
    ),
    SandwichPattern(
        'chc',
        'k',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        5,
    ),
    SandwichPattern(
        'chs',
        'xe',
        frozenset({'a'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'cowe',
        'kow',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'd',
        't',
        frozenset({'r'}),
        frozenset({'el'}),
        0,
    ),
    SandwichPattern(
        'tz',
        'tte',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        4,
    ),
    SandwichPattern(
        'ts',
        'tte',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        4,
    ),
    SandwichPattern(
        'e',
        'z',
        frozenset({'s'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'e',
        'o',
        frozenset({'s'}),
        frozenset({'n-'}),
        4,
    ),
    SandwichPattern(
        'ee',
        'ea',
        frozenset({'-r'}),
        frozenset({'d-'}),
        0,
    ),
    SandwichPattern(
        'ee',
        'y',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'ie',
        'y',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'ee',
        'ie',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'er',
        'ore',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'ey',
        'y',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'l',
        'hl',
        frozenset({'a', 'e', 'i', 'o', 'u', 'y'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'i',
        'y',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        4,
    ),
    SandwichPattern(
        'i',
        'y',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        4,
    ),
    SandwichPattern(
        'i',
        'e',
        frozenset({'g'}),
        frozenset({'n'}),
        4,
    ),
    SandwichPattern(
        'iy',
        'y',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'ian',
        'ienne',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'k',
        'c',
        frozenset({'-'}),
        frozenset({'oh'}),
        0,
    ),
    SandwichPattern(
        'kow',
        'cow',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'l',
        '',
        frozenset({'co'}),
        frozenset({'m-'}),
        5,
    ),
    SandwichPattern(
        'le',
        'el',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'ma',
        'na',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'o',
        'a',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'n-'}),
        5,
    ),
    SandwichPattern(
        'ole',
        'ol',
        frozenset({'-'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        4,
    ),
    SandwichPattern(
        'ole',
        'ol',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        4,
    ),
    SandwichPattern(
        'oo',
        'oa',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'r'}),
        0,
    ),
    SandwichPattern(
        'orf',
        'of',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'orf',
        'off',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'orff',
        'of',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'ou',
        'oe',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        5,
    ),
    SandwichPattern(
        'ow',
        'ou',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        0,
    ),
    SandwichPattern(
        'ow',
        'au',
        frozenset({'-', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        0,
    ),
    SandwichPattern(
        'owl',
        'ol',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'k'}),
        0,
    ),
    SandwichPattern(
        'ri',
        'e',
        frozenset({'f'}),
        frozenset({'d'}),
        6,
    ),
    SandwichPattern(
        'ron',
        'an',
        frozenset({'f'}),
        frozenset({'t'}),
        5,
    ),
    SandwichPattern(
        's',
        'z',
        frozenset({'t'}),
        frozenset({'e'}),
        0,
    ),
    SandwichPattern(
        's',
        'c',
        frozenset({'a'}),
        frozenset({'e'}),
        0,
    ),
    SandwichPattern(
        'sc',
        's',
        frozenset({'-'}),
        frozenset({'h'}),
        0,
    ),
    SandwichPattern(
        'toun',
        'town',
        frozenset({'-'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        0,
    ),
    SandwichPattern(
        'ts',
        'z',
        frozenset({'n'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'tt',
        'd',
        frozenset({'a'}),
        frozenset({'el'}),
        0,
    ),
    SandwichPattern(
        'tt',
        'dd',
        frozenset({'a'}),
        frozenset({'el'}),
        0,
    ),
    SandwichPattern(
        'tz',
        'z',
        frozenset({'n'}),
        frozenset({'-'}),
        0,
    ),
    SandwichPattern(
        'u',
        'oo',
        frozenset({'l'}),
        frozenset({'s'}),
        5,
    ),
    SandwichPattern(
        'ue',
        'uc',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'k'}),
        0,
    ),
    SandwichPattern(
        'ue',
        'e',
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'w'}),
        0,
    ),
    SandwichPattern(
        'coch',
        'koche',
        frozenset({'-'}),
        frozenset({'r'}),
        0,
    ),
    SandwichPattern(
        'c',
        's',
        frozenset({'-', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'e'}),
        0,
    ),
    SandwichPattern(
        'one',
        'onde',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        0,
    ),
    SandwichPattern(
        'rr',
        'n',
        frozenset({'a'}),
        frozenset({'e'}),
        6,
    ),
    SandwichPattern(
        'r',
        'n',
        frozenset({'a'}),
        frozenset({'e'}),
        6,
    ),
    SandwichPattern(
        'b',
        'p',
        frozenset({'a', 'e', 'i', 'o', 'u', 'y'}),
        frozenset({'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'}),
        5,
    ),
    SandwichPattern(
        'au',
        'ou',
        frozenset({'-', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'-', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        5,
    ),
    SandwichPattern(
        'ikh',
        'ih',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'o'}),
        5,
    ),
    SandwichPattern(
        'ik',
        'ih',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'o'}),
        5,
    ),
    SandwichPattern(
        'ea',
        'eu',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'hl'}),
        5,
    ),
    SandwichPattern(
        'ea',
        'euh',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'eah',
        'eu',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'l'}),
        5,
    ),
    SandwichPattern(
        'dt',
        'd',
        frozenset({'n'}),
        frozenset({'-'}),
        5,
    ),
    SandwichPattern(
        'tt',
        'd',
        frozenset({'u'}),
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        5,
    ),
    SandwichPattern(
        'odo',
        'ette',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        8,
    ),
    SandwichPattern(
        'ode',
        'ette',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        5,
    ),
    SandwichPattern(
        'odde',
        'ette',
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        frozenset({'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}),
        5,
    ),
    SandwichPattern(
        'ow',
        'ui',
        frozenset({'br'}),
        frozenset({'n'}),
        0,
    ),
    SandwichPattern(
        'ow',
        'u',
        frozenset({'br'}),
        frozenset({'n'}),
        0,
    ),
}
